# Generated by Django 5.1.7 on 2025-03-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('premium', 'Premium')], default='basic', max_length=100),
        ),
    ]
