# Generated by Django 5.1.7 on 2025-03-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_alter_license_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
